user www-data;
worker_processes auto;
pid /run/nginx.pid;
error_log /var/log/nginx/error.log;
include /etc/nginx/modules-enabled/*.conf;

events {
	worker_connections 5000;
	use epoll;
	multi_accept on;
}

http {
        keepalive_timeout 600;
        keepalive_requests 10000;
	sendfile on;
	tcp_nopush on;
	types_hash_max_size 2048;
	include /etc/nginx/mime.types;
	access_log /var/log/nginx/access.log;
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
	ssl_prefer_server_ciphers on;
	gzip on;

	server {
		listen 81 default_server;
		location /rtmp/ {
			fastcgi_pass unix:/run/php/php-fpm.sock;
			fastcgi_param SCRIPT_FILENAME /var/www/html/rtmp/auth.php;
			include fastcgi_params;
		}
	}
